(cl:in-package practice-msg)
(cl:export '(HEADER-VAL
          HEADER
          UAV0_PX-VAL
          UAV0_PX
          UAV0_PY-VAL
          UAV0_PY
          UAV0_PZ-VAL
          UAV0_PZ
          UAV1_PX-VAL
          UAV1_PX
          UAV1_PY-VAL
          UAV1_PY
          UAV1_PZ-VAL
          UAV1_PZ
          UAV2_PX-VAL
          UAV2_PX
          UAV2_PY-VAL
          UAV2_PY
          UAV2_PZ-VAL
          UAV2_PZ
          G0_PX-VAL
          G0_PX
          G0_PY-VAL
          G0_PY
          G0_PZ-VAL
          G0_PZ
          G1_PX-VAL
          G1_PX
          G1_PY-VAL
          G1_PY
          G1_PZ-VAL
          G1_PZ
          G2_PX-VAL
          G2_PX
          G2_PY-VAL
          G2_PY
          G2_PZ-VAL
          G2_PZ
          TIME-VAL
          TIME
          UAV0_PID_VX-VAL
          UAV0_PID_VX
          UAV0_PID_VY-VAL
          UAV0_PID_VY
          UAV0_PID_VZ-VAL
          UAV0_PID_VZ
          UAV0_AS-VAL
          UAV0_AS
          UAV0_A_VX-VAL
          UAV0_A_VX
          UAV0_A_VY-VAL
          UAV0_A_VY
          UAV0_A_VZ-VAL
          UAV0_A_VZ
          UAV0_CS-VAL
          UAV0_CS
          UAV0_C_VX-VAL
          UAV0_C_VX
          UAV0_C_VY-VAL
          UAV0_C_VY
          UAV0_C_VZ-VAL
          UAV0_C_VZ
          UAV1_PID_VX-VAL
          UAV1_PID_VX
          UAV1_PID_VY-VAL
          UAV1_PID_VY
          UAV1_PID_VZ-VAL
          UAV1_PID_VZ
          UAV1_AS-VAL
          UAV1_AS
          UAV1_A_VX-VAL
          UAV1_A_VX
          UAV1_A_VY-VAL
          UAV1_A_VY
          UAV1_A_VZ-VAL
          UAV1_A_VZ
          UAV1_CS-VAL
          UAV1_CS
          UAV1_C_VX-VAL
          UAV1_C_VX
          UAV1_C_VY-VAL
          UAV1_C_VY
          UAV1_C_VZ-VAL
          UAV1_C_VZ
          UAV2_PID_VX-VAL
          UAV2_PID_VX
          UAV2_PID_VY-VAL
          UAV2_PID_VY
          UAV2_PID_VZ-VAL
          UAV2_PID_VZ
          UAV2_AS-VAL
          UAV2_AS
          UAV2_A_VX-VAL
          UAV2_A_VX
          UAV2_A_VY-VAL
          UAV2_A_VY
          UAV2_A_VZ-VAL
          UAV2_A_VZ
          UAV2_CS-VAL
          UAV2_CS
          UAV2_C_VX-VAL
          UAV2_C_VX
          UAV2_C_VY-VAL
          UAV2_C_VY
          UAV2_C_VZ-VAL
          UAV2_C_VZ
))