// Generated by gencpp from file practice/information.msg
// DO NOT EDIT!


#ifndef PRACTICE_MESSAGE_INFORMATION_H
#define PRACTICE_MESSAGE_INFORMATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace practice
{
template <class ContainerAllocator>
struct information_
{
  typedef information_<ContainerAllocator> Type;

  information_()
    : point()
    , vel()  {
    }
  information_(const ContainerAllocator& _alloc)
    : point(_alloc)
    , vel(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _vel_type;
  _vel_type vel;





  typedef boost::shared_ptr< ::practice::information_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::practice::information_<ContainerAllocator> const> ConstPtr;

}; // struct information_

typedef ::practice::information_<std::allocator<void> > information;

typedef boost::shared_ptr< ::practice::information > informationPtr;
typedef boost::shared_ptr< ::practice::information const> informationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::practice::information_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::practice::information_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::practice::information_<ContainerAllocator1> & lhs, const ::practice::information_<ContainerAllocator2> & rhs)
{
  return lhs.point == rhs.point &&
    lhs.vel == rhs.vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::practice::information_<ContainerAllocator1> & lhs, const ::practice::information_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace practice

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::practice::information_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::practice::information_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::practice::information_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::practice::information_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::practice::information_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::practice::information_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::practice::information_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f9c1875cae7e508fddc892d11872297";
  }

  static const char* value(const ::practice::information_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f9c1875cae7e508ULL;
  static const uint64_t static_value2 = 0xfddc892d11872297ULL;
};

template<class ContainerAllocator>
struct DataType< ::practice::information_<ContainerAllocator> >
{
  static const char* value()
  {
    return "practice/information";
  }

  static const char* value(const ::practice::information_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::practice::information_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point point\n"
"geometry_msgs/Vector3 vel\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::practice::information_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::practice::information_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct information_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::practice::information_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::practice::information_<ContainerAllocator>& v)
  {
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRACTICE_MESSAGE_INFORMATION_H
